### ISSUE TITLE
First deploy: error with the build_platform/ folder

### ISSUE THREAD

**Issue by flovntp** [platformsh-templates/API-Platform-v3#1]
during first deploy, this error is trigger.
```
 GENERATED
        W: node:internal/fs/utils:347
        W:     throw err;
        W:     ^
        W:
        W: Error: ENOENT: no such file or directory, open 'build_platform/index.html'
        W:     at Object.openSync (node:fs:594:3)
        W:     at Object.readFileSync (node:fs:462:35)
        W:     at /app/node_modules/platformsh_variables/createJson.js:46:23
        W:     at /app/node_modules/platformsh_variables/node_modules/webpack/lib/Compiler.js:272:15
        W:     at Compiler.emitRecords (/app/node_modules/platformsh_variables/node_modules/webpack/lib/Compiler.js:367:37)
        W:     at /app/node_modules/platformsh_variables/node_modules/webpack/lib/Compiler.js:265:12
        W:     at /app/node_modules/platformsh_variables/node_modules/webpack/lib/Compiler.js:360:11
        W:     at next (/app/node_modules/platformsh_variables/node_modules/tapable/lib/Tapable.js:218:11)
        W:     at Compiler.<anonymous> (/app/node_modules/platformsh_variables/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
        W:     at Compiler.applyPluginsAsyncSeries1 (/app/node_modules/platformsh_variables/node_modules/tapable/lib/Tapable.js:222:13) {
        W:   errno: -2,
        W:   syscall: 'open',
        W:   code: 'ENOENT',
        W:   path: 'build_platform/index.html'
        W: }
        W: error Command failed with exit code 1.
```

**Comment by flovntp** [comment]
Solved
